### ISSUE TITLE
[FR] Possible to return for just the field focused on?

### ISSUE THREAD

**Issue by ejntaylor** [Juhlinus/kakunin#1]
Fantastic work. 

Currently I have a form of 10 required fields. When I start to enter text on the first input I trigger the validation check and it returns errors for all the other fields at the same time.

Quite jarring for the user as they had not yet started to look at those fields and the errors were not displayed on page load.

Perhaps there is a way to offer the error message for the specific input currently focused on?

Any ideas on best approach here?

Thanks!

<img width="802" alt="image" src="https://user-images.githubusercontent.com/2080025/91183411-58ccc180-e6e3-11ea-9894-da8a64199e1d.png">

**Comment by Juhlinus** [comment]
@raisonon Thanks buddy, this has been fixed in [v1.1.0](https://github.com/Juhlinus/kakunin/releases/tag/v1.1.0). 😄
